// src/app/shared/components/card/card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-card',
  standalone: true,
  template: `
    <div [class]="'rounded-2xl border border-gray-200 bg-white p-8 shadow-sm ' + extraClass">
      <ng-content />
    </div>
  `,
})
export class CardComponent {
  @Input() extraClass = '';
}

// src/components/ui/Card.tsx
import type { ReactNode } from "react";

interface CardProps {
  children: ReactNode;
  className?: string;
}

export function Card({ children, className = "" }: CardProps) {
  return (
    <div
      className={`rounded-2xl border border-gray-200 bg-white p-8 shadow-sm ${className}`}
    >
      {children}
    </div>
  );
}
